server:
  port: ${PORT:3333}

spring:
  application:
    name: service-b
  data:
    mongodb:
      uri: mongodb://mongo:mongo@192.168.0.111
      database: mydb

logging:
  level:
    com.bakigoal: DEBUG

kafka:
  bootstrapAddress: 192.168.0.111:29092
  topics:
    resource_b_changed: resource_b_changed_topic