server:
  port: ${PORT:3333}

spring:
  application:
    name: service-b
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb
      database: mydb

logging:
  level:
    com.bakigoal: DEBUG