apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: micro.all
      http:
        paths:
          - path: /a
            pathType: Prefix
            backend:
              service:
                name: service-a
                port:
                  number: 2222
          - path: /b
            pathType: Prefix
            backend:
              service:
                name: service-b
                port:
                  number: 3333