server:
  port: ${PORT:2222}

spring:
  application:
    name: service-a
  redis:
    url: redis://192.168.0.111:6379

services:
  service-b:
    url: http://localhost:3333/

logging:
  level:
    com.bakigoal: DEBUG

kafka:
  bootstrapAddress: 192.168.0.111:29092
  consumer:
    topic.name: resource_b_changed_topic
    groupid: service-a